//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Черновик.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialList
    {
        public string MaterialType { get; set; }
        public int ID { get; set; }
        public string Title { get; set; }
        public int CountInPack { get; set; }
        public string Unit { get; set; }
        public Nullable<double> CountInStock { get; set; }
        public double MinCount { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public string Image { get; set; }
        public int MaterialTypeID { get; set; }
        public string Supplier { get; set; }
        public Nullable<bool> NormCountInStock { get; set; }
        public Nullable<bool> BigCountInStock { get; set; }
    }
}
